#!/usr/bin/env bash
FROM python:3

COPY requirements.txt /

RUN pip install -r requirements.txt


COPY . /

EXPOSE 8000

RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
CMD ["sh", "-c", "tail -f /dev/null"]